#!/bin/bash

cd ~/folder/util/mactools
if [ $# != 0  ] ; then
    git add . && git commit -am "update config" && git push origin master
else
    git status&&git pull
fi 

echo "================DOTVIM================"
cd ~/.vim/dotvim && git status && git pull && cd ~
