#!/bin/bash

echo -e "\n================sync folder/util...================\n"
cd ~/folder/util/mactools
if [ $# != 0  ] ; then
    git add . && git commit -am "update config" && git push origin master
else
    git status&&git pull
fi 

echo -e "\n================sync .vim/dotvim...================\n"
cd ~/.vim/dotvim
if [ $# != 0  ] ; then
    git add . && git commit -am "cmt" && git push origin master
else
    git status && git pull 
fi 

cd ~

